GET {{host}}/echo
Accept: application/json

### GET request with parameter
GET {{host}}/echo
Accept: application/json

### GET request with parameter
GET {{host}}/echo
Accept: application/json

### GET request with parameter
GET {{host}}/echo
Accept: application/json

### GET request with parameter
GET {{host}}/echo
Accept: application/json

