#!/bin/bash

# Check for errors and warnings
go vet ./... || exit

# Generate version and git commit
# go generate ./... || exit

# Format your code
go fmt ./... || exit

golangci-lint run || exit

go test -v -race -cover -covermode=atomic -count=1 ./... || exit
