// Code generated by RonyKIT Stub Generator (Golang); DO NOT EDIT.

package sampleservice

import (
	"context"
	"fmt"

	"github.com/clubpay/ronykit/kit"
	"github.com/clubpay/ronykit/stub"
	"github.com/clubpay/ronykit/x/rkit"
	"github.com/clubpay/ronykit/x/rkit/reflector"
)

var (
	_ fmt.Stringer
	_ rkit.SpinLock
)

func init() {
	reflector.Register(&EchoRequest{}, "json")
	reflector.Register(&EchoResponse{}, "json")
	reflector.Register(&EmbeddedHeader{}, "json")
	reflector.Register(&ErrorMessage{}, "json")
	reflector.Register(&RedirectRequest{}, "json")
	reflector.Register(&SumRequest{}, "json")
	reflector.Register(&SumResponse{}, "json")
}

type IStub interface {
	EchoGET(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error)

	EchoPOST(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error)

	Sum1(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	Sum2(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	SumRedirect(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	Upload(
		ctx context.Context,
		req kit.MultipartFormMessage,
		opt ...stub.RESTOption,
	) (kit.RawMessage, error)
}

// EchoRequest is a data transfer object
type EchoRequest struct {
	RandomID         int64   `json:"randomID"`
	Ok               bool    `json:"ok"`
	OptionalStrField *string `json:"optionalField" swag:"enum:a,b,c"`
	OptionalIntField *int64  `json:"optionalIntField"`
}

type EchoRequest_OptionalStrFieldENUM = string

const (
	EchoRequest_OptionalStrField_A = "a"
	EchoRequest_OptionalStrField_B = "b"
	EchoRequest_OptionalStrField_C = "c"
)

// EchoResponse is a data transfer object
type EchoResponse struct {
	RandomID         int64   `json:"randomID"`
	Ok               bool    `json:"ok"`
	OptionalStrField *string `json:"optionalField"`
	OptionalIntField *int64  `json:"optionalIntField"`
}

// EmbeddedHeader is a data transfer object
type EmbeddedHeader struct {
	SomeKey1 string `json:"someKey1"`
	SomeInt1 int64  `json:"someInt1"`
}

// ErrorMessage is a data transfer object
type ErrorMessage struct {
	Code int    `json:"code"`
	Item string `json:"item"`
}

func (x ErrorMessage) GetCode() int {
	return x.Code
}

func (x ErrorMessage) GetItem() string {
	return x.Item
}

// RedirectRequest is a data transfer object
type RedirectRequest struct {
	URL string `json:"url"`
}

// SumRequest is a data transfer object
type SumRequest struct {
	EmbeddedHeader
	Val1 int64 `json:"val1"`
	Val2 int64 `json:"val2"`
}

// SumResponse is a data transfer object
type SumResponse struct {
	EmbeddedHeader
	Val int64 `json:"val"`
}

// Stub represents the client/stub for .
// Implements IStub
type Stub struct {
	s *stub.Stub
}

func NewStub(hostPort string, opts ...stub.Option) *Stub {
	s := &Stub{
		s: stub.New(hostPort, opts...),
	}

	return s
}

// Client returns the underlying stub.Stub used by generated REST methods.
// It is not part of IStub so existing mock implementations stay valid.
func (s Stub) Client() *stub.Stub {
	return s.s
}

var _ IStub = (*Stub)(nil)

// EchoGET GET /echo/{randomID}
func (s Stub) EchoGET(
	ctx context.Context, req *EchoRequest, opt ...stub.RESTOption,
) (*EchoResponse, error) {

	res := &EchoResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/echo/{randomID}", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// EchoPOST POST /echo-post
func (s Stub) EchoPOST(
	ctx context.Context, req *EchoRequest, opt ...stub.RESTOption,
) (*EchoResponse, error) {

	res := &EchoResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/echo-post", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// Sum1 GET /sum/{val1}/{val2}
func (s Stub) Sum1(
	ctx context.Context, req *SumRequest, opt ...stub.RESTOption,
) (*SumResponse, error) {

	res := &SumResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/sum/{val1}/{val2}", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// Sum2 POST /sum
func (s Stub) Sum2(
	ctx context.Context, req *SumRequest, opt ...stub.RESTOption,
) (*SumResponse, error) {

	res := &SumResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/sum", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// SumRedirect GET /sum-redirect/{val1}/{val2}
func (s Stub) SumRedirect(
	ctx context.Context, req *SumRequest, opt ...stub.RESTOption,
) (*SumResponse, error) {

	res := &SumResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/sum-redirect/{val1}/{val2}", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// Upload POST /upload
func (s Stub) Upload(
	ctx context.Context, req kit.MultipartFormMessage, opt ...stub.RESTOption,
) (kit.RawMessage, error) {

	res := kit.RawMessage{}

	httpCtx := s.s.REST(opt...).
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				res = rkit.CloneBytes(r.GetBody())
				return nil

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/upload", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

type MockOption func(*StubMock)

func MockEchoGET(
	f func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error),
) MockOption {
	return func(sm *StubMock) {
		sm.echoGET = f
	}
}

func MockEchoPOST(
	f func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error),
) MockOption {
	return func(sm *StubMock) {
		sm.echoPOST = f
	}
}

func MockSum1(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) MockOption {
	return func(sm *StubMock) {
		sm.sum1 = f
	}
}

func MockSum2(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) MockOption {
	return func(sm *StubMock) {
		sm.sum2 = f
	}
}

func MockSumRedirect(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) MockOption {
	return func(sm *StubMock) {
		sm.sumRedirect = f
	}
}

func MockUpload(
	f func(
		ctx context.Context,
		req kit.MultipartFormMessage,
		opt ...stub.RESTOption,
	) (kit.RawMessage, error),
) MockOption {
	return func(sm *StubMock) {
		sm.upload = f
	}
}

// StubMock represents the mocked for client/stub for .
// Implements IStub
type StubMock struct {
	echoGET func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error)

	echoPOST func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error)

	sum1 func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	sum2 func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	sumRedirect func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error)

	upload func(
		ctx context.Context,
		req kit.MultipartFormMessage,
		opt ...stub.RESTOption,
	) (kit.RawMessage, error)
}

func NewStubMock(opts ...MockOption) *StubMock {
	s := &StubMock{}
	for _, o := range opts {
		o(s)
	}

	return s
}

var _ IStub = (*StubMock)(nil)

func (s *StubMock) EchoGET(
	ctx context.Context,
	req *EchoRequest,
	opt ...stub.RESTOption,
) (*EchoResponse, error) {
	if s.echoGET == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.echoGET(ctx, req, opt...)
}

func (s *StubMock) SetEchoGET(
	f func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error),
) *StubMock {
	s.echoGET = f

	return s
}

func (s *StubMock) EchoPOST(
	ctx context.Context,
	req *EchoRequest,
	opt ...stub.RESTOption,
) (*EchoResponse, error) {
	if s.echoPOST == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.echoPOST(ctx, req, opt...)
}

func (s *StubMock) SetEchoPOST(
	f func(
		ctx context.Context,
		req *EchoRequest,
		opt ...stub.RESTOption,
	) (*EchoResponse, error),
) *StubMock {
	s.echoPOST = f

	return s
}

func (s *StubMock) Sum1(
	ctx context.Context,
	req *SumRequest,
	opt ...stub.RESTOption,
) (*SumResponse, error) {
	if s.sum1 == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.sum1(ctx, req, opt...)
}

func (s *StubMock) SetSum1(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) *StubMock {
	s.sum1 = f

	return s
}

func (s *StubMock) Sum2(
	ctx context.Context,
	req *SumRequest,
	opt ...stub.RESTOption,
) (*SumResponse, error) {
	if s.sum2 == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.sum2(ctx, req, opt...)
}

func (s *StubMock) SetSum2(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) *StubMock {
	s.sum2 = f

	return s
}

func (s *StubMock) SumRedirect(
	ctx context.Context,
	req *SumRequest,
	opt ...stub.RESTOption,
) (*SumResponse, error) {
	if s.sumRedirect == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.sumRedirect(ctx, req, opt...)
}

func (s *StubMock) SetSumRedirect(
	f func(
		ctx context.Context,
		req *SumRequest,
		opt ...stub.RESTOption,
	) (*SumResponse, error),
) *StubMock {
	s.sumRedirect = f

	return s
}

func (s *StubMock) Upload(
	ctx context.Context,
	req kit.MultipartFormMessage,
	opt ...stub.RESTOption,
) (kit.RawMessage, error) {
	if s.upload == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.upload(ctx, req, opt...)
}

func (s *StubMock) SetUpload(
	f func(
		ctx context.Context,
		req kit.MultipartFormMessage,
		opt ...stub.RESTOption,
	) (kit.RawMessage, error),
) *StubMock {
	s.upload = f

	return s
}
