version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - godot
    - godox
    - gosec
    - ireturn
    - mnd
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - recvcheck
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - unused
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        whitelist:
          list-mode: lax
          files:
            - $all
            - '!*_test.go'
          deny:
            - pkg: io/ioutil
              desc: io/ioutil is deprecated, use io instead
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
