linters:
  enable-all: true
  disable:
    - wsl
    - scopelint
    - tparallel
    - gomnd
    - forcetypeassert
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - funlen
    - godot
    - dupl
  fast: true

