version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - depguard
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - intrange
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        whitelist:
          list-mode: lax
          files:
            - $all
            - '!*_test.go'
          deny:
            - pkg: io/ioutil
              desc: io/ioutil is deprecated, use io instead
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
