run:
  tests: false
linters:
  enable-all: true
  disable:
    - wsl
    - gomnd
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - funlen
    - godot
    - godox
    - nonamedreturns
    - testpackage
    - tagliatelle
    - scopelint
    - exhaustivestruct
    - exhaustruct
    - maligned
    - wrapcheck
    - varnamelen
    - ireturn
    - varcheck
    - nosnakecase
    - interfacer
    - golint
    - ifshort
    - deadcode
    - structcheck
    - depguard
    - tagalign
  fast: true
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true
  cyclop:
    max-complexity: 15

