run:
  tests: false
linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - funlen
    - godot
    - godox
    - nonamedreturns
    - testpackage
    - tagliatelle
    - exhaustruct
    - wrapcheck
    - varnamelen
    - ireturn
    - depguard
    - perfsprint
    - mnd
    - gosec
  fast: false
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true
  cyclop:
    max-complexity: 15
  depguard:
    rules:
      whitelist:
        list-mode: lax
        files:
          - $all
          - "!*_test.go"
        deny:
          - pkg: "io/ioutil"
            desc: "io/ioutil is deprecated, use io instead"



