// Code generated by RonyKIT Stub Generator (TypeScript); DO NOT EDIT.

// ErrorMessage is a data transfer object
export interface ErrorMessage {
	code: number;
	item: string;
}

// KeyValue is a data transfer object
export interface KeyValue {
	key: string;
	value: number;
}

// SimpleHdr is a data transfer object
export interface SimpleHdr {
	sKey1: string;
	sKey2: number;
	t1: string;
	t2: string | null;
	t3: string[] | null;
}

// VeryComplexRequest is a data transfer object
export interface VeryComplexRequest extends SimpleHdr {
	key1: string;
	key1Ptr: string | null;
	key2Ptr?: number;
	mapKey1: { [key: string]: number } | null;
	mapKey2: { [key: number]: KeyValue } | null;
	sliceKey1: boolean[] | null;
	sliceKey2: KeyValue[] | null;
	rawKey: any | null;
}
export type VeryComplexRequest_Key1Ptr = "a" | "b" | "c";

// VeryComplexResponse is a data transfer object
export interface VeryComplexResponse {
	key1?: string;
	key1Ptr?: string;
	mapKey1?: { [key: string]: number };
	mapKey2?: { [key: number]: KeyValue };
	sliceKey1: string | null;
	sliceKey2: KeyValue[] | null;
	printer: any;
}

export class sampleServiceStubError extends globalThis.Error {
	readonly status: number;
	readonly body: string;

	constructor(status: number, body: string) {
		super(`Failed to fetch the data (${status}): ${body}`);
		this.name = "sampleServiceStubError";
		this.status = status;
		this.body = body;
	}
}

export class sampleServiceStub {
	readonly serverURL: string;
	private readonly defaultInit: RequestInit;

	constructor(serverURL: string, defaultInit?: RequestInit) {
		this.serverURL = serverURL.replace(/\/$/, "");
		this.defaultInit = defaultInit ?? {};
	}

	private async fetchJSON<T>(path: string, init: RequestInit): Promise<T> {
		const res = await fetch(`${this.serverURL}${path}`, {
			...this.defaultInit,
			...init,
			headers: {
				...(this.defaultInit.headers as Record<string, string> | undefined),
				...(init.headers as Record<string, string> | undefined),
			},
		});
		if (res.status !== 200 && res.status !== 201 && res.status !== 202) {
			throw new sampleServiceStubError(res.status, await res.text());
		}

		const text = await res.text();
		if (!text) {
			return undefined as T;
		}

		return JSON.parse(text) as T;
	}

	private buildQuery(
		req: Record<string, unknown>,
		pathParams: string[],
	): string {
		const exclude = new Set(pathParams);
		const query = new URLSearchParams();
		for (const [key, value] of Object.entries(req)) {
			if (exclude.has(key) || value === undefined || value === null) {
				continue;
			}
			if (Array.isArray(value)) {
				for (const item of value) {
					if (item !== undefined && item !== null && typeof item !== "object") {
						query.append(key, String(item));
					}
				}
				continue;
			}
			if (typeof value === "object") {
				continue;
			}
			query.append(key, String(value));
		}
		const qs = query.toString();
		return qs ? `?${qs}` : "";
	}

	async complexDummy(
		req: VeryComplexRequest,
		headers?: HeadersInit,
		init?: RequestInit,
	): Promise<VeryComplexResponse> {
		return this.fetchJSON<VeryComplexResponse>(`/complexDummy`, {
			method: "POST",
			...init,
			headers: {
				"Content-Type": "application/json",
				...headers,
				...init?.headers,
			},
			body: JSON.stringify(req),
		});
	}
	async complexDummy2(
		req: VeryComplexRequest,
		headers?: HeadersInit,
		init?: RequestInit,
	): Promise<VeryComplexResponse> {
		return this.fetchJSON<VeryComplexResponse>(
			`/complexDummy/${encodeURIComponent(String(req.key1))}`,
			{
				method: "POST",
				...init,
				headers: {
					"Content-Type": "application/json",
					...headers,
					...init?.headers,
				},
				body: JSON.stringify(req),
			},
		);
	}
	async getComplexDummy(
		req: VeryComplexRequest,
		headers?: HeadersInit,
		init?: RequestInit,
	): Promise<VeryComplexResponse> {
		const queryParams = this.buildQuery(req as Record<string, unknown>, [
			"key1",
			"sKey1",
		]);
		return this.fetchJSON<VeryComplexResponse>(
			`/complexDummy/${encodeURIComponent(String(req.key1))}/xs/${encodeURIComponent(String(req.sKey1))}${queryParams}`,
			{
				method: "GET",
				...init,
				headers: {
					...headers,
					...init?.headers,
				},
			},
		);
	}
}
