"use client";

// Code generated by RonyKIT Stub Generator (TypeScript); DO NOT EDIT.
import useSWR, { SWRConfiguration } from "swr";
import {
	sampleServiceStub,
	VeryComplexRequest,
	VeryComplexResponse,
} from "./stub";

export function useComplexDummy(
	stub: sampleServiceStub,
	req: VeryComplexRequest,
	reqHeader?: HeadersInit,
	options?: Partial<SWRConfiguration<VeryComplexResponse>>,
	init?: RequestInit,
) {
	return useSWR(
		[req, "ComplexDummy"],
		([req]) => stub.complexDummy(req, reqHeader, init),
		options,
	);
}
export function useComplexDummy2(
	stub: sampleServiceStub,
	req: VeryComplexRequest,
	reqHeader?: HeadersInit,
	options?: Partial<SWRConfiguration<VeryComplexResponse>>,
	init?: RequestInit,
) {
	return useSWR(
		[req, "ComplexDummy2"],
		([req]) => stub.complexDummy2(req, reqHeader, init),
		options,
	);
}
export function useGetComplexDummy(
	stub: sampleServiceStub,
	req: VeryComplexRequest,
	reqHeader?: HeadersInit,
	options?: Partial<SWRConfiguration<VeryComplexResponse>>,
	init?: RequestInit,
) {
	return useSWR(
		[req, "GetComplexDummy"],
		([req]) => stub.getComplexDummy(req, reqHeader, init),
		options,
	);
}
