version: "2"
output:
  path-prefix: backend/pkg/bkit
linters:
  default: all
  disable:
    - cyclop
    - errorlint
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - ireturn
    - mnd
    - nonamedreturns
    - revive
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/orlangure/gnomock
            - github.com/goccy/go-reflec
            - github.com/jinzhu/copier
            - gopkg.in/yaml.v3
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
