// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// Generated At: 2025-03-05 12:09:32.128207 +0300 +03 m=+0.015050567

package boxship

import "github.com/blang/semver/v4"

var Version = semver.MustParse("0.0.4")
