// Code generated by RonyKIT Stub Generator (Golang); DO NOT EDIT.

package sampleservicestub

import (
	"context"

	"github.com/clubpay/ronykit"
	"github.com/clubpay/ronykit/stub"
)

// EchoRequest is a data transfer object
type EchoRequest struct {
	RandomID int64 `json:"randomID"`
	Ok       bool  `json:"ok"`
}

// EchoResponse is a data transfer object
type EchoResponse struct {
	RandomID int64 `json:"randomID"`
	Ok       bool  `json:"ok"`
}

// EmbeddedHeader is a data transfer object
type EmbeddedHeader struct {
	SomeKey1 string `json:"someKey1"`
	SomeInt1 int64  `json:"someInt1"`
}

// RedirectRequest is a data transfer object
type RedirectRequest struct {
	URL string `json:"url"`
}

// SumRequest is a data transfer object
type SumRequest struct {
	EmbeddedHeader
	Val1 int64 `json:"val1"`
	Val2 int64 `json:"val2"`
}

// SumResponse is a data transfer object
type SumResponse struct {
	EmbeddedHeader
	Val int64
}

// SampleServiceStub represents the client/stub for SampleService.
type SampleServiceStub struct {
	hostPort  string
	secure    bool
	verifyTLS bool

	s *stub.Stub
}

func NewSampleServiceStub(hostPort string, opts ...stub.Option) *SampleServiceStub {
	s := &SampleServiceStub{
		s: stub.New(hostPort, opts...),
	}

	return s
}

func (s SampleServiceStub) Echo(req *EchoRequest) (*EchoResponse, *stub.Error) {
	res := &EchoResponse{}
	err := s.s.REST().
		SetMethod("GET").
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun("/echo/:randomID", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) Sum1(req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("GET").
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun("/sum/:val1/:val2", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) Sum2(req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("POST").
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun("/sum", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) SumRedirect(req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("GET").
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun("/sum-redirect/:val1/:val2", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}
