// Code generated by RonyKIT Stub Generator (Golang); DO NOT EDIT.

package sampleservicestub

import (
	"context"

	"github.com/clubpay/ronykit"
	"github.com/clubpay/ronykit/stub"
	"github.com/clubpay/ronykit/utils/reflector"
)

func init() {
	reflector.Register(&EchoRequest{})
	reflector.Register(&EchoResponse{})
	reflector.Register(&EmbeddedHeader{})
	reflector.Register(&ErrorMessage{})
	reflector.Register(&RedirectRequest{})
	reflector.Register(&SumRequest{})
	reflector.Register(&SumResponse{})
}

// EchoRequest is a data transfer object
type EchoRequest struct {
	RandomID int64 `json:"randomID"`
	Ok       bool  `json:"ok"`
}

// EchoResponse is a data transfer object
type EchoResponse struct {
	RandomID int64 `json:"randomID"`
	Ok       bool  `json:"ok"`
}

// EmbeddedHeader is a data transfer object
type EmbeddedHeader struct {
	SomeKey1 string `json:"someKey1"`
	SomeInt1 int64  `json:"someInt1"`
}

// ErrorMessage is a data transfer object
type ErrorMessage struct {
	Code int    `json:"code"`
	Item string `json:"item"`
}

// RedirectRequest is a data transfer object
type RedirectRequest struct {
	URL string `json:"url"`
}

// SumRequest is a data transfer object
type SumRequest struct {
	EmbeddedHeader
	Val1 int64 `json:"val1"`
	Val2 int64 `json:"val2"`
}

// SumResponse is a data transfer object
type SumResponse struct {
	EmbeddedHeader
	Val int64 `json:"val"`
}

// SampleServiceStub represents the client/stub for SampleService.
type SampleServiceStub struct {
	hostPort  string
	secure    bool
	verifyTLS bool

	s *stub.Stub
}

func NewSampleServiceStub(hostPort string, opts ...stub.Option) *SampleServiceStub {
	s := &SampleServiceStub{
		s: stub.New(hostPort, opts...),
	}

	return s
}

func (s SampleServiceStub) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, *stub.Error) {
	res := &EchoResponse{}
	err := s.s.REST().
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(400, "INPUT", res)
			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun(ctx, "/echo/:randomID", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) Sum1(ctx context.Context, req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(400, "INPUT", res)
			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun(ctx, "/sum/:val1/:val2", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) Sum2(ctx context.Context, req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(400, "INPUT", res)
			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun(ctx, "/sum", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}

func (s SampleServiceStub) SumRedirect(ctx context.Context, req *SumRequest) (*SumResponse, *stub.Error) {
	res := &SumResponse{}
	err := s.s.REST().
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(400, "INPUT", res)
			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.WrapError(ronykit.UnmarshalMessage(r.GetBody(), res))
			},
		).
		AutoRun(ctx, "/sum-redirect/:val1/:val2", ronykit.JSON, req).
		Err()
	if err != nil {
		return nil, err
	}

	return res, nil
}
