version: "2"
run:
  tests: false
linters:
  disable:
    - depguard
    - errcheck
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - gosec
    - ireturn
    - mnd
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        whilelist:
          list-mode: lax
          files:
            - $all
            - '!*_test.go'
          deny:
            - pkg: io/ioutil
              desc: io/ioutil is deprecated, use io instead
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
