// Code generated by RonyKIT Stub Generator (Golang); DO NOT EDIT.

package sampleservice

import (
	"context"
	"fmt"
	"time"

	"github.com/clubpay/ronykit/kit"
	"github.com/clubpay/ronykit/stub"
	"github.com/clubpay/ronykit/x/rkit"
	"github.com/clubpay/ronykit/x/rkit/reflector"
)

var (
	_ fmt.Stringer
	_ rkit.SpinLock

	_ time.Time
)

func init() {
	reflector.Register(&ErrorMessage{}, "json")
	reflector.Register(&KeyValue{}, "json")
	reflector.Register(&SimpleHdr{}, "json")
	reflector.Register(&VeryComplexRequest{}, "json")
	reflector.Register(&VeryComplexResponse{}, "json")
}

type IsampleServiceStub interface {
	ComplexDummy(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)

	ComplexDummy2(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)

	GetComplexDummy(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)
}

// ErrorMessage is a data transfer object
type ErrorMessage struct {
	Code int    `json:"code"`
	Item string `json:"item"`
}

func (x ErrorMessage) GetCode() int {
	return x.Code
}

func (x ErrorMessage) GetItem() string {
	return x.Item
}

// KeyValue is a data transfer object
type KeyValue struct {
	Key   string `json:"key"`
	Value int    `json:"value"`
}

// SimpleHdr is a data transfer object
type SimpleHdr struct {
	Key1 string      `json:"sKey1"`
	Key2 int         `json:"sKey2"`
	T1   time.Time   `json:"t1"`
	T2   *time.Time  `json:"t2"`
	T3   []time.Time `json:"t3"`
}

// VeryComplexRequest is a data transfer object
type VeryComplexRequest struct {
	SimpleHdr
	Key1      string             `json:"key1"`
	Key1Ptr   *string            `json:"key1Ptr" swag:"enum:a,b,c"`
	Key2Ptr   *int               `json:"key2Ptr,omitempty"`
	MapKey1   map[string]int     `json:"mapKey1"`
	MapKey2   map[int64]KeyValue `json:"mapKey2"`
	SliceKey1 []bool             `json:"sliceKey1"`
	SliceKey2 []*KeyValue        `json:"sliceKey2"`
	RawKey    kit.JSONMessage    `json:"rawKey"`
}

type VeryComplexRequest_Key1PtrENUM = string

const (
	VeryComplexRequest_Key1Ptr_A = "a"
	VeryComplexRequest_Key1Ptr_B = "b"
	VeryComplexRequest_Key1Ptr_C = "c"
)

// VeryComplexResponse is a data transfer object
type VeryComplexResponse struct {
	Key1      string              `json:"key1,omitempty" swag:"enum:1,2,3;deprecated"`
	Key1Ptr   *string             `json:"key1Ptr,omitempty"`
	MapKey1   map[string]int      `json:"mapKey1,omitempty"`
	MapKey2   map[int64]*KeyValue `json:"mapKey2,omitempty"`
	SliceKey1 []uint8             `json:"sliceKey1"`
	SliceKey2 []KeyValue          `json:"sliceKey2"`
	NoOutput  int                 `json:"-"`
	Printer   any                 `json:"printer"`
}

// sampleServiceStub represents the client/stub for sampleService.
// Implements IsampleServiceStub
type sampleServiceStub struct {
	s *stub.Stub
}

func NewsampleServiceStub(hostPort string, opts ...stub.Option) *sampleServiceStub {
	s := &sampleServiceStub{
		s: stub.New(hostPort, opts...),
	}

	return s
}

// Client returns the underlying stub.Stub used by generated REST methods.
// It is not part of IsampleServiceStub so existing mock implementations stay valid.
func (s sampleServiceStub) Client() *stub.Stub {
	return s.s
}

var _ IsampleServiceStub = (*sampleServiceStub)(nil)

// ComplexDummy POST /complexDummy
func (s sampleServiceStub) ComplexDummy(
	ctx context.Context, req *VeryComplexRequest, opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {

	res := &VeryComplexResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		AutoRun(ctx, "/complexDummy", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// ComplexDummy2 POST /complexDummy/{key1}
func (s sampleServiceStub) ComplexDummy2(
	ctx context.Context, req *VeryComplexRequest, opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {

	res := &VeryComplexResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("POST").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		AutoRun(ctx, "/complexDummy/{key1}", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

// GetComplexDummy GET /complexDummy/{key1}/xs/{sKey1}
func (s sampleServiceStub) GetComplexDummy(
	ctx context.Context, req *VeryComplexRequest, opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {

	res := &VeryComplexResponse{}

	httpCtx := s.s.REST(opt...).
		SetMethod("GET").
		SetResponseHandler(
			400,
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				res := &ErrorMessage{}
				err := stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))
				if err != nil {
					return err
				}

				return stub.NewErrorWithMsg(res)
			},
		).
		SetOKHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {

				return stub.WrapError(kit.UnmarshalMessage(r.GetBody(), res))

			},
		).
		DefaultResponseHandler(
			func(ctx context.Context, r stub.RESTResponse) *stub.Error {
				return stub.NewError(r.StatusCode(), string(r.GetBody()))
			},
		).
		AutoRun(ctx, "/complexDummy/{key1}/xs/{sKey1}", kit.CustomEncoding("json"), req)
	defer httpCtx.Release()

	if err := httpCtx.Err(); err != nil {
		return nil, err
	}

	return res, nil
}

type MockOption func(*sampleServiceStubMock)

func MockComplexDummy(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) MockOption {
	return func(sm *sampleServiceStubMock) {
		sm.complexDummy = f
	}
}

func MockComplexDummy2(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) MockOption {
	return func(sm *sampleServiceStubMock) {
		sm.complexDummy2 = f
	}
}

func MockGetComplexDummy(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) MockOption {
	return func(sm *sampleServiceStubMock) {
		sm.getComplexDummy = f
	}
}

// sampleServiceStubMock represents the mocked for client/stub for sampleService.
// Implements IsampleServiceStub
type sampleServiceStubMock struct {
	complexDummy func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)

	complexDummy2 func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)

	getComplexDummy func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error)
}

func NewsampleServiceStubMock(opts ...MockOption) *sampleServiceStubMock {
	s := &sampleServiceStubMock{}
	for _, o := range opts {
		o(s)
	}

	return s
}

var _ IsampleServiceStub = (*sampleServiceStubMock)(nil)

func (s *sampleServiceStubMock) ComplexDummy(
	ctx context.Context,
	req *VeryComplexRequest,
	opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {
	if s.complexDummy == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.complexDummy(ctx, req, opt...)
}

func (s *sampleServiceStubMock) SetComplexDummy(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) *sampleServiceStubMock {
	s.complexDummy = f

	return s
}

func (s *sampleServiceStubMock) ComplexDummy2(
	ctx context.Context,
	req *VeryComplexRequest,
	opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {
	if s.complexDummy2 == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.complexDummy2(ctx, req, opt...)
}

func (s *sampleServiceStubMock) SetComplexDummy2(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) *sampleServiceStubMock {
	s.complexDummy2 = f

	return s
}

func (s *sampleServiceStubMock) GetComplexDummy(
	ctx context.Context,
	req *VeryComplexRequest,
	opt ...stub.RESTOption,
) (*VeryComplexResponse, error) {
	if s.getComplexDummy == nil {
		return nil, stub.WrapError(fmt.Errorf("method not mocked"))
	}

	return s.getComplexDummy(ctx, req, opt...)
}

func (s *sampleServiceStubMock) SetGetComplexDummy(
	f func(
		ctx context.Context,
		req *VeryComplexRequest,
		opt ...stub.RESTOption,
	) (*VeryComplexResponse, error),
) *sampleServiceStubMock {
	s.getComplexDummy = f

	return s
}
